import json
import os

notebook_path = os.path.join(os.getcwd(), "LoRA_Auto_Curation_Colab.ipynb")

cells = []

# Markdown cell
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 📄 LoRA 黃金訓練集自動篩選系統 (Colab 雲端版)\n",
        "本 Notebook 專為 Google Colab 環境設計，提供 Google Drive 掛載功能、參數設定表單、GPU 自動偵測，以及嚴格的起飛前置檢查 (Pre-flight checks)。內建感知雜湊 (dHash) 去重防護網與訓練集多樣性診斷教練。"
    ]
})

# Code cell 1
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# @title 1. 掛載 Google Drive 與安裝必要套件\n",
        "from google.colab import drive\n",
        "import os\n",
        "\n",
        "print('🔄 正在掛載 Google Drive...')\n",
        "drive.mount('/content/drive')\n",
        "\n",
        "print('📦 正在安裝必要套件 (這可能需要幾十秒鐘)...')\n",
        "!pip install -q insightface onnxruntime-gpu opencv-python numpy\n",
        "print('✅ 環境建置完成！')"
    ]
})

# Code cell 2
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# @title 2. 專案路徑與篩選變數設定 { display-mode: \"form\" }\n",
        "import os\n",
        "\n",
        "# 將專案建立在雲端硬碟的某個資料夾下\n",
        "PROJECT_ROOT = '/content/drive/MyDrive/LoRA_Auto_Curation' # @param {type:\"string\"}\n",
        "INPUT_DIR_NAME = 'raw_data' # @param {type:\"string\"}\n",
        "OUTPUT_DIR_NAME = 'LoRA_Curated_Dataset' # @param {type:\"string\"}\n",
        "\n",
        "BLUR_THRESHOLD = 150.0 # @param {type:\"number\"}\n",
        "MIN_FACE_RATIO = 0.05 # @param {type:\"number\"}\n",
        "DET_THRESH = 0.6 # @param {type:\"number\"}\n",
        "\n",
        "INPUT_DIR = os.path.join(PROJECT_ROOT, INPUT_DIR_NAME)\n",
        "OUTPUT_DIR = os.path.join(PROJECT_ROOT, OUTPUT_DIR_NAME)\n",
        "\n",
        "print(f\"📁 專案根目錄: {PROJECT_ROOT}\")\n",
        "print(f\"📥 待篩選圖片路徑 (來源): {INPUT_DIR}\")\n",
        "print(f\"📤 篩選後輸出路徑 (目標): {OUTPUT_DIR}\")\n",
        "\n",
        "os.makedirs(INPUT_DIR, exist_ok=True)\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "print('\\n✅ 目錄結構已準備完成。請確認您的原始圖片已放入「待篩選圖片路徑」中，再執行後續儲存格！')"
    ]
})

# Code cell 3
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# @title 3. 核心引擎載入與起飛前置檢查 (Pre-flight checks)\n",
        "import sys\n",
        "import cv2\n",
        "import shutil\n",
        "import numpy as np\n",
        "import onnxruntime as ort\n",
        "import insightface\n",
        "from insightface.app import FaceAnalysis\n",
        "\n",
        "MODEL_NAME = 'buffalo_l'\n",
        "INSIGHTFACE_MODEL_DIR = os.path.expanduser(f'~/.insightface/models/{MODEL_NAME}')\n",
        "\n",
        "def pre_flight_checks():\n",
        "    print('\\n' + '='*50)\n",
        "    print('🛫 [Pre-flight Check] 啟動前置檢查程序...')\n",
        "    print('='*50)\n",
        "    \n",
        "    if not os.path.exists(INPUT_DIR) or not os.listdir(INPUT_DIR):\n",
        "        print(f'❌ [錯誤/警告] 來源資料夾不存在或為空: {INPUT_DIR}')\n",
        "        print('💡 請先將待訓練的圖片上傳到 Google Drive 的該資料夾中，否則無法進行篩選！')\n",
        "    else:\n",
        "        print(f'✅ [檢查通過] 來源資料夾存在且包含檔案: {INPUT_DIR}')\n",
        "        \n",
        "    if not os.path.exists(OUTPUT_DIR):\n",
        "        os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "    print(f'✅ [檢查通過] 輸出資料夾已確認: {OUTPUT_DIR}')\n",
        "\n",
        "    required_model_file = os.path.join(INSIGHTFACE_MODEL_DIR, 'det_10g.onnx')\n",
        "    if not os.path.exists(required_model_file):\n",
        "        print(f'⚠️ [警告] 找不到 InsightFace 模型核心檔案: {required_model_file}')\n",
        "        print('>> 系統將在稍後初始化時自動嘗試下載模型。這可能需要一些時間。')\n",
        "    else:\n",
        "        print(f'✅ [檢查通過] 偵測到模型已完整下載: {INSIGHTFACE_MODEL_DIR}')\n",
        "        \n",
        "    print('='*50)\n",
        "    print('🚀 變數與環境檢查完畢，準備起飛！\\n')\n",
        "    \n",
        "    return {\n",
        "        'input_dir': INPUT_DIR,\n",
        "        'output_dir': OUTPUT_DIR,\n",
        "        'blur_threshold': BLUR_THRESHOLD,\n",
        "        'min_face_ratio': MIN_FACE_RATIO,\n",
        "        'det_thresh': DET_THRESH,\n",
        "        'model_name': MODEL_NAME\n",
        "    }\n",
        "\n",
        "class LoRACurator:\n",
        "    def __init__(self, run_config):\n",
        "        self.blur_threshold = run_config['blur_threshold']\n",
        "        self.min_face_ratio = run_config['min_face_ratio']\n",
        "        self.det_thresh = run_config['det_thresh']\n",
        "        self.model_name = run_config['model_name']\n",
        "        \n",
        "        print('\\n' + '='*50)\n",
        "        print('🤖 [Init] 啟動黃金資料篩選引擎')\n",
        "        print('='*50)\n",
        "        \n",
        "        available_providers = ort.get_available_providers()\n",
        "        if 'CUDAExecutionProvider' in available_providers:\n",
        "            print('>> 🟢 [環境偵測] 偵測到 GPU (CUDA)，將啟動極速掃描模式。')\n",
        "            cuda_options = {'arena_extend_strategy': 'kSameAsRequested'}\n",
        "            providers = [('CUDAExecutionProvider', cuda_options), 'CPUExecutionProvider']\n",
        "        else:\n",
        "            print('>> 🟡 [環境偵測] 未偵測到 GPU，系統自動切換為純 CPU 模式執行。')\n",
        "            providers = ['CPUExecutionProvider']\n",
        "            \n",
        "        self.app = FaceAnalysis(name=self.model_name, providers=providers)\n",
        "        self.app.prepare(ctx_id=0, det_size=(640, 640), det_thresh=self.det_thresh)\n",
        "\n",
        "    def get_image_hash(self, image, hash_size=8):\n",
        "        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\n",
        "        resized = cv2.resize(gray, (hash_size + 1, hash_size))\n",
        "        diff = resized[:, 1:] > resized[:, :-1]\n",
        "        return sum([2 ** i for (i, v) in enumerate(diff.flatten()) if v])\n",
        "\n",
        "    def measure_blurriness(self, image):\n",
        "        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\n",
        "        return cv2.Laplacian(gray, cv2.CV_64F).var()\n",
        "\n",
        "    def get_pose_label(self, pose):\n",
        "        pitch, yaw, roll = pose\n",
        "        if yaw > 25: return '右側臉'\n",
        "        if yaw < -25: return '左側臉'\n",
        "        if pitch > 20: return '俯角'\n",
        "        if pitch < -20: return '仰角'\n",
        "        return '標準正臉'\n",
        "\n",
        "    def evaluate_image(self, img_path):\n",
        "        img = cv2.imread(img_path)\n",
        "        if img is None: return False, 'Reject_ReadError', None\n",
        "\n",
        "        blur_score = self.measure_blurriness(img)\n",
        "        if blur_score < self.blur_threshold:\n",
        "            return False, 'Reject_Blurry', f'(銳利度 {blur_score:.1f} 不及格)'\n",
        "\n",
        "        faces = self.app.get(img)\n",
        "        if len(faces) == 0: return False, 'Reject_NoFace', '(找不到符合標準的人臉)'\n",
        "        if len(faces) > 1: return False, 'Reject_MultiFace', f'(偵測到 {len(faces)} 張臉)'\n",
        "\n",
        "        face = faces[0]\n",
        "        h, w = img.shape[:2]\n",
        "        box_area = (face.bbox[2] - face.bbox[0]) * (face.bbox[3] - face.bbox[1])\n",
        "        face_ratio = box_area / (h * w)\n",
        "        if face_ratio < self.min_face_ratio:\n",
        "            return False, 'Reject_TooSmall', f'(臉部佔比 {face_ratio*100:.1f}% 太小)'\n",
        "\n",
        "        pose_label = self.get_pose_label(face.pose)\n",
        "        return True, 'Accepted', f'[{pose_label}] 銳利度:{blur_score:.0f}, 佔比:{face_ratio*100:.1f}%'\n"
    ]
})

# Code cell 4
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# @title 4. 開始執行篩選\n",
        "run_config = pre_flight_checks()\n",
        "\n",
        "output_dir = run_config['output_dir']\n",
        "accepted_dir = os.path.join(output_dir, 'Accepted')\n",
        "os.makedirs(accepted_dir, exist_ok=True)\n",
        "\n",
        "input_dir = run_config['input_dir']\n",
        "curator = LoRACurator(run_config)\n",
        "\n",
        "print(f'\\n📂 開始掃描目錄: {input_dir}')\n",
        "print(f'📁 合格圖檔將儲存至: {accepted_dir}')\n",
        "print('-' * 50)\n",
        "\n",
        "stats = {'Accepted': 0, 'Rejected': 0, 'Duplicated': 0}\n",
        "pose_counts = {\n",
        "    '標準正臉': 0,\n",
        "    '左側臉': 0,\n",
        "    '右側臉': 0,\n",
        "    '仰角': 0,\n",
        "    '俯角': 0\n",
        "}\n",
        "\n",
        "existing_hashes = set()\n",
        "existing_accepted_count = 0\n",
        "print('🔍 正在建立已收錄圖片的防重指紋庫與分析歷史資料...')\n",
        "if os.path.exists(accepted_dir):\n",
        "    for existing_file in os.listdir(accepted_dir):\n",
        "        if existing_file.lower().endswith(('.jpg', '.png', '.jpeg', '.webp')):\n",
        "            img_path = os.path.join(accepted_dir, existing_file)\n",
        "            img = cv2.imread(img_path)\n",
        "            if img is not None:\n",
        "                existing_hashes.add(curator.get_image_hash(img))\n",
        "                existing_accepted_count += 1\n",
        "                \n",
        "                # 重新辨識既有圖片的姿勢\n",
        "                faces = curator.app.get(img)\n",
        "                if len(faces) > 0:\n",
        "                    pose_label = curator.get_pose_label(faces[0].pose)\n",
        "                    if pose_label in pose_counts:\n",
        "                        pose_counts[pose_label] += 1\n",
        "print(f'🔒 防護網啟動：已紀錄 {len(existing_hashes)} 張圖的指紋，並載入歷史姿勢數據。\\n')\n",
        "\n",
        "valid_extensions = ('.jpg', '.png', '.jpeg', '.webp')\n",
        "\n",
        "for filename in os.listdir(input_dir):\n",
        "    if not filename.lower().endswith(valid_extensions): \n",
        "        continue\n",
        "        \n",
        "    filepath = os.path.join(input_dir, filename)\n",
        "    \n",
        "    img = cv2.imread(filepath)\n",
        "    if img is not None:\n",
        "        img_hash = curator.get_image_hash(img)\n",
        "        if img_hash in existing_hashes:\n",
        "            print(f'♻️ [剔除] {filename} -> (重複圖片，已收錄過)')\n",
        "            rej_dir = os.path.join(output_dir, 'Reject_Duplicate')\n",
        "            os.makedirs(rej_dir, exist_ok=True)\n",
        "            shutil.copy(filepath, os.path.join(rej_dir, filename))\n",
        "            stats['Duplicated'] += 1\n",
        "            continue\n",
        "            \n",
        "    passed, status_dir, info = curator.evaluate_image(filepath)\n",
        "    \n",
        "    if passed:\n",
        "        print(f'✅ [合格] {filename} -> {info}')\n",
        "        shutil.copy(filepath, os.path.join(accepted_dir, filename))\n",
        "        stats['Accepted'] += 1\n",
        "        existing_hashes.add(img_hash)\n",
        "        \n",
        "        for pose_type in pose_counts.keys():\n",
        "            if pose_type in info:\n",
        "                pose_counts[pose_type] += 1\n",
        "                break\n",
        "    else:\n",
        "        print(f'❌ [剔除] {filename} -> {info}')\n",
        "        rej_dir = os.path.join(output_dir, status_dir)\n",
        "        os.makedirs(rej_dir, exist_ok=True)\n",
        "        shutil.copy(filepath, os.path.join(rej_dir, filename))\n",
        "        stats['Rejected'] += 1\n",
        "\n",
        "print('\\n' + '='*50)\n",
        "print(f'📊 篩選完成報告')\n",
        "print(f\"總處理數: {stats['Accepted'] + stats['Rejected'] + stats['Duplicated']} 張\")\n",
        "print(f\"✨ 黃金訓練圖 (合格): {stats['Accepted']} 張 (已存入 {accepted_dir})\")\n",
        "print(f\"🗑️ 淘汰圖片 (不合格): {stats['Rejected']} 張\")\n",
        "print(f\"♻️ 重複圖片 (已收錄): {stats['Duplicated']} 張\")\n",
        "print('='*50)\n",
        "\n",
        "print('\\n' + '='*50)\n",
        "print('🩺 LoRA 訓練集健康度診斷報告')\n",
        "print('='*50)\n",
        "\n",
        "total_accepted = stats['Accepted'] + existing_accepted_count\n",
        "if total_accepted == 0:\n",
        "    print('目前尚無任何合格圖片，請開始搜集資料！')\n",
        "else:\n",
        "    print('【目前整體角度庫存佔比 (含歷史收錄)】')\n",
        "    for pose, count in pose_counts.items():\n",
        "        percent = (count / total_accepted) * 100\n",
        "        print(f'  - {pose:5s}: {count:2d} 張 ({percent:.1f}%)')\n",
        "        \n",
        "    print('\\n【💡 AI 教練搜圖建議】')\n",
        "    target_total = 25 \n",
        "    \n",
        "    if total_accepted < 15:\n",
        "        print(f'⚠️ [張數不足] 目前僅有 {total_accepted} 張。建議總量需達到 {target_total} 張，請再搜集至少 {target_total - total_accepted} 張高品質照片。')\n",
        "    elif total_accepted > 35:\n",
        "        print(f'⚠️ [張數過多] 目前有 {total_accepted} 張。資料量太大可能導致訓練失焦，建議手動刪除一些特徵過於相近的照片。')\n",
        "    else:\n",
        "        print(f'✅ [張數達標] 目前 {total_accepted} 張，落在 15~35 張的最佳訓練區間！')\n",
        "\n",
        "    front_ratio = pose_counts['標準正臉'] / total_accepted\n",
        "    side_ratio = (pose_counts['左側臉'] + pose_counts['右側臉']) / total_accepted\n",
        "    \n",
        "    if front_ratio > 0.6:\n",
        "        print(f'🚨 [嚴重失衡] 正臉比例高達 {front_ratio*100:.0f}%！未來模型側臉會崩壞。')\n",
        "        print('   👉 下一步行動：請『停止』搜集正面照！請專門去搜尋目標人物的【側臉】與【轉頭】照片。')\n",
        "        \n",
        "    if pose_counts['左側臉'] == 0 or pose_counts['右側臉'] == 0:\n",
        "        print('🚨 [結構缺失] 缺乏側臉輪廓！AI 無法建構 3D 深度。')\n",
        "        if pose_counts['左側臉'] == 0: print('   👉 請去搜尋目標人物【看向畫面左邊】的照片。')\n",
        "        if pose_counts['右側臉'] == 0: print('   👉 請去搜尋目標人物【看向畫面右邊】的照片。')\n",
        "\n",
        "    if pose_counts['仰角'] == 0 and pose_counts['俯角'] == 0:\n",
        "        print('⚠️ [多樣性不足] 缺乏高低視角。這會限制未來合成仰角或低頭底圖的能力。')\n",
        "        print('   👉 下一步行動：可尋找微抬下巴，或鏡頭從上往下拍的日常照片。')\n",
        "\n",
        "    if front_ratio <= 0.6 and side_ratio >= 0.2 and pose_counts['左側臉'] > 0 and pose_counts['右側臉'] > 0:\n",
        "        print('🌟 [完美平衡] 您的資料集角度非常均衡！具備了煉製極品 LoRA 的潛力！')\n",
        "        \n",
        "print('='*50)\n"
    ]
})

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": []
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": cells
}

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print(f"Notebook generated at: {notebook_path}")
